//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringTools.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StringTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;div&gt;$CT$&lt;/div&gt;
        ///&lt;pre class=&quot;line&quot;&gt;
        ///$CMD$
        ///&lt;/pre&gt;
        /// 的本地化字符串。
        /// </summary>
        internal static string CmdContent {
            get {
                return ResourceManager.GetString("CmdContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StringTools V 1.0 
        ///又叫字符串处理工具，是墨云开发的转为处理字符串的工具。
        ///    包含对字符串处理的各种命令，可以通过该工具方便的对
        ///字符串进行替换、重组、按模板生成等。
        ///    更可以通过cmd***系列命令对工具命令集进行添加修改删
        ///除等操作。如cmdview开可以打开图形化界面查看命令,cmdadd 
        ///添加新的命令,通过cmdupdate修改命令，配置完成后重新生成
        ///CSScript(C#)脚本，重启工具更新程序。
        ///    说明字符串通配符说明：
        ///    \s   空格
        ///    \t   tab
        ///    \d   空值
        ///    \n   换行
        ///命令加载时默认对该部分数据进行转换，如果不需要转换，
        ///例如，使用到了正则比表达，本身不需要转义所以在配置命
        ///令时，请记住设置关闭转义 可通过：
        ///    cmdupdate regex 
        ///命令查看相关配置。
        ///    如果对于部分内容需要转义，请使用Tools脚本中提供的
        ///转义方法进行处理，可通过
        ///    cmdupdate repregex
        ///命令查看脚本编写方式。
        ///
        ///    要查看命令信息，可以通过  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string helpContent {
            get {
                return ResourceManager.GetString("helpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;div&gt;$OT$&lt;/div&gt;
        ///&lt;pre class=&quot;content&quot;&gt;
        ///$OP$
        ///&lt;/pre&gt; 的本地化字符串。
        /// </summary>
        internal static string IOContent {
            get {
                return ResourceManager.GetString("IOContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            font-family: Helvetica, arial, freesans, clean, sans-serif;
        ///            font-size: 14px;
        ///            line-height: 1.6;
        ///            color: #333;
        ///            background-color: aliceblue;
        ///        }
        ///
        ///        .main {
        ///            max-width: 960px;
        ///            margin: 0 auto;
        ///        }
        ///
        ///        .title {
        ///          [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MainContent {
            get {
                return ResourceManager.GetString("MainContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似     &lt;div class=&quot;run&quot;&gt;
        ///        &lt;label &gt;$CMD$&lt;/label&gt;
        ///        &lt;div class=&quot;desc&quot;&gt;
        ///            $DSC$
        ///        &lt;/div&gt;
        ///        
        ///         $CNT$
        /// 
        ///    &lt;/div&gt; 的本地化字符串。
        /// </summary>
        internal static string RunContent {
            get {
                return ResourceManager.GetString("RunContent", resourceCulture);
            }
        }
    }
}
